baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Artem Smirnov Blog'
theme = 'ananke'

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"


# Google Cloud Storage -- see https://gocloud.dev/howto/blob/#gcs
URL = "gs://super_bucket_999"
